version: '3'

services:

  api_service:
  nginx:
    build:
      context: ./docker-configs/nginx/
      dockerfile: Dockerfile
    environment:
      - NGINX_SERVER_NAME=domain.com
    ports:
      - 80:80
      - 443:443
